### PR TITLE
added more userID revolvers for reactions

### PR DESCRIPTION
**Pull request by CheweyZ**

### CODE REVIEW

**Comment by CheweyZ** [comment]
Ive got no idea whats going on with indents it shows normaly in my commit but in diffs it looks so wrong maybe someone else needs to check

**Comment by cloudrac3r** [comment]
The problem with the indentation appears to be because you used spaces for indentation whereas the rest of discord.io uses tabs. Change all your spaces to tabs and that should fix the indentation.

**Comment by Woor** [comment]
Ugh, thanks for the info, no idea how that could have happened though. oO

**Comment by Woor** [comment]
ty :)

**Pull request merged**
